# Generated by Django 2.2.6 on 2019-10-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
