# Generated by Django 2.2.6 on 2019-10-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_products', '0002_auto_20191011_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
